new features and refactoring
hyoo-ru/studio.mol.hyoo.ru pull request #12
Opened 2023-04-09 15:21 UTC by stan-donarise

- редактирование словарей (dict).
- небольшие свойства раскрываются автоматически.
- выбор класса для object и типа для list интегрированы в селектор типа.
- добавил страницу readme компонентов, компонент выбирается кликом по карточке  (репозиторий для readme в экспандере донор-приложения).
- разделил код для значений разных типов по классам ($hyoo_studio_value - $mol_ghost фабрика, все value-классы наследуются от $hyoo_studio_value_unit).

2023-04-09 16:50 UTC, nin-jin requested changes

2023-04-09 16:50 UTC, nin-jin commented on prop/prop.view.tree
> +		click? <=> show_info? null
А это зачем? Очень подозрительный код.

2023-04-09 16:50 UTC, nin-jin commented on prop/prop.view.ts
> +			event?.stopPropagation()
Этот метод лучше никогда не использовать - он ломает логику внешних компонент.

2023-04-09 16:50 UTC, nin-jin commented on value/bound/bound.view.ts
> +		}
`this.toString()` тут не подойдёт?

2023-04-09 16:50 UTC, nin-jin commented on value/list/list.view.tree
> +					props_of!klass <= props_of!klass $mol_tree2_empty
Поправишь на звёздочки?

2023-04-09 16:54 UTC, stan-donarise commented on prop/prop.view.tree
> +		click? <=> show_info? null
Для выбора компонента в readme странице, т.е. клик в любом месте на карточке свойства открывает его readme

2023-04-09 17:01 UTC, stan-donarise commented on value/list/list.view.tree
> +					props_of!klass <= props_of!klass $mol_tree2_empty
Хотелось оставить подчеркнутым то, что здесь не id используется для props_of (вообще наверное надо покрасивее сделать всю эту передачу свойств)

2023-04-09 17:03 UTC, stan-donarise commented on prop/prop.view.ts
> +			event?.stopPropagation()
https://github.com/hyoo-ru/studio.hyoo.ru/pull/12#discussion_r1161313339
Для этого надо было.. тогда отказываться от такой возможности - клик в любом месте

2023-04-09 17:06 UTC, stan-donarise commented on value/bound/bound.view.ts
> +		}
да, должен подойти..

2023-04-11 08:54 UTC, nin-jin commented on prop/prop.view.tree
> +		click? <=> show_info? null
Открытие страницы переносит фокус на неё и скроллит к ней. Да и если пользователь с чем-то взаимодействует, это не значит, что он хочет терять текущую доку и открывать другую. Я бы сделал это через $mol_check_icon.

2023-04-11 08:55 UTC, nin-jin commented on prop/prop.view.ts
> +			event?.stopPropagation()
Даже если ге-то потребуется такая функциональность, то лучше использовать `preventDefaut`.

2023-04-15 02:52 UTC, stan-donarise commented on value/bound/bound.view.ts
> +		}
Поменял на `this.toString()`

2023-04-15 02:52 UTC, stan-donarise commented on prop/prop.view.tree
> +		click? <=> show_info? null
Сделал $mol_check_icon для базового класса, для свойств пока ничего..

2023-04-15 02:53 UTC, stan-donarise commented on prop/prop.view.ts
> +			event?.stopPropagation()
Убрал это.

2023-04-15 11:10 UTC, nin-jin commented on studio.view.ts
> +			this.readme_module_name( next )
Какой-то подозрительный код, что он делает?

2023-04-15 11:15 UTC, nin-jin commented on value/list/list.view.tree
> +					props_of!klass <= props_of!klass $mol_tree2_empty
В любом случае восклицательные знаки хотелось бы когда-нибудь убрать.

2023-04-15 13:03 UTC, stan-donarise commented on studio.view.ts
> +			this.readme_module_name( next )
Передает модуль в readme страницу. Сделал немного по-другому.

2023-04-15 13:03 UTC, stan-donarise commented on value/list/list.view.tree
> +					props_of!klass <= props_of!klass $mol_tree2_empty
Исправил.

2023-04-16 16:32 UTC, nin-jin approved these changes

2023-04-16 16:32 UTC, merged

2023-04-16 16:45 UTC, nin-jin commented
```
		\hyoo/studio/prop/type/type.view.ts(40,43): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Partial<{ bind: "<=>"; get: "<="; put: "=>"; }>'.
		\  No index signature with a parameter of type 'string' was found on type 'Partial<{ bind: "<=>"; get: "<="; put: "=>"; }>'.
```

2023-04-16 16:52 UTC, stan-donarise commented
> ```
> \hyoo/studio/prop/type/type.view.ts(40,43): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Partial<{ bind: "<=>"; get: "<="; put: "=>"; }>'.
> \  No index signature with a parameter of type 'string' was found on type 'Partial<{ bind: "<=>"; get: "<="; put: "=>"; }>'.
> ```

Такого файла: `hyoo/studio/prop/type/type.view.ts` уже нет.

тут вот такая ошибка вроде: 
`\mol/wire/graph/graph.ts(15,39): error TS2551: Property 'pub_list' does not exist on type '$mol_wire_pub'. Did you mean 'sub_list'?`
https://github.com/hyoo-ru/studio.hyoo.ru/actions/runs/4714304370/jobs/8360578181#step:2:749

2023-04-16 17:23 UTC, nin-jin commented
Поправил.